// Build the unified preview page: compile each dist/<Name>/<Name>.jsx via esbuild,
// emit dist-esm/<Name>/<Name>.js (with react imports rewritten to esm.sh proxies),
// then write dist-esm/*-esm.mjs proxy modules, preview/index.html (without importmap),
// and preview/preview.js (dynamic-import loop).
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import * as esbuild from 'esbuild';
import { renderPreviewHtml } from '../templates/preview.html.mjs';

const REACT_PROXY_URL = 'https://esm.sh/react@18';
const REACT_DOM_CLIENT_PROXY_URL = 'https://esm.sh/react-dom@18/client';

// Post-process an esbuild output file: rewrite bare `react` / `react-dom/client`
// imports to relative paths pointing at the proxy modules in dist-esm/.
// Depends on render-react.mjs emitting a single-line `import React from 'react';`
// form (line 171 of v1). If render-react.mjs changes its import shape, this
// function must be updated too.
function rewriteReactImports(esmSrc) {
  let out = esmSrc;
  out = out.replace(
    /from\s+['"]react['"]/g,
    `from '../react-esm.mjs'`
  );
  out = out.replace(
    /from\s+['"]react-dom\/client['"]/g,
    `from '../react-dom-client-esm.mjs'`
  );
  return out;
}

async function writeProxy(distEsmDir, filename, body) {
  const path = join(distEsmDir, filename);
  await writeFile(path, body, 'utf8');
  return path;
}

export async function buildPreview({ workdir }) {
  const distDir = join(workdir, 'dist');
  const distEsmDir = join(workdir, 'dist-esm');
  const previewDir = join(workdir, 'preview');

  const entries = await readdir(distDir, { withFileTypes: true });
  const componentDirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);
  if (componentDirs.length === 0) {
    throw new Error('No components found under ' + distDir);
  }

  await mkdir(distEsmDir, { recursive: true });
  await mkdir(previewDir, { recursive: true });

  // 1. esbuild each component JSX → dist-esm/<Name>/<Name>.js, with bare react
  //    imports kept external (so we can rewrite them in step 2).
  for (const name of componentDirs) {
    const entry = join(distDir, name, `${name}.jsx`);
    const outDir = join(distEsmDir, name);
    await mkdir(outDir, { recursive: true });
    await esbuild.build({
      entryPoints: [entry],
      outfile: join(outDir, `${name}.js`),
      format: 'esm',
      jsx: 'automatic',
      bundle: true,
      loader: { '.js': 'jsx', '.jsx': 'jsx' },
      external: ['react', 'react-dom', 'react-dom/client'],
      logLevel: 'silent',
    });
  }

  // 2. Rewrite bare react imports in each compiled file to point at esm.sh proxies.
  //    Then write the two proxy modules.
  for (const name of componentDirs) {
    const outFile = join(distEsmDir, name, `${name}.js`);
    const src = await readFile(outFile, 'utf8');
    const rewritten = rewriteReactImports(src);
    if (rewritten !== src) {
      await writeFile(outFile, rewritten, 'utf8');
    }
  }

  await writeProxy(
    distEsmDir,
    'react-esm.mjs',
    `// Auto-generated by build-preview; do not edit by hand.\n` +
      `export { default } from '${REACT_PROXY_URL}';\n` +
      `export * from '${REACT_PROXY_URL}';\n`
  );
  await writeProxy(
    distEsmDir,
    'react-dom-client-esm.mjs',
    `// Auto-generated by build-preview; do not edit by hand.\n` +
      `export * from '${REACT_DOM_CLIENT_PROXY_URL}';\n`
  );

  // 3. preview/index.html (no importmap).
  await writeFile(join(previewDir, 'index.html'), renderPreviewHtml(componentDirs), 'utf8');

  // 4. preview/preview.js — dynamic-import loop, no bare react specifiers.
  const mountArr = JSON.stringify(componentDirs);
  const previewJs =
    `// Auto-generated by build-preview; do not edit by hand.\n` +
    `const components = ${mountArr};\n` +
    `const { createRoot } = await import('../dist-esm/react-dom-client-esm.mjs');\n` +
    `for (const name of components) {\n` +
    `  try {\n` +
    `    const mod = await import(\`../dist-esm/\${name}/\${name}.js\`);\n` +
    `    const el = document.getElementById(\`mount-\${name}\`);\n` +
    `    if (el && mod.default) {\n` +
    `      const root = createRoot(el);\n` +
    `      root.render(mod.default());\n` +
    `    }\n` +
    `  } catch (e) {\n` +
    `    console.error(\`Failed to render \${name}:\`, e);\n` +
    `  }\n` +
    `}\n`;
  await writeFile(join(previewDir, 'preview.js'), previewJs, 'utf8');

  return { components: componentDirs, outputDir: previewDir };
}
